# development:
#   cloud_name: <%= ENV["du7zs0x7r"]%>
#   api_key: <%= ENV['212524798127239'] %>
#   api_secret: <%= ENV['33clEac02MyGIsZFaud3Sp-Os3Y'] 
#   enhance_image_tag: true
#   static_file_support: false
# production:
#   cloud_name: <%= ENV["du7zs0x7r"]%>
#   api_key: <%= ENV['212524798127239'] %>
#   api_secret: <%= ENV['33clEac02MyGIsZFaud3Sp-Os3Y'] 
#   enhance_image_tag: true
#   static_file_support: false
# test:
#   cloud_name: <%= ENV["du7zs0x7r"]%>
#   api_key: <%= ENV['212524798127239'] %>
#   api_secret: <%= ENV['33clEac02MyGIsZFaud3Sp-Os3Y'] 
#   enhance_image_tag: true
#   static_file_support: false